# src/optimization.py
from __future__ import annotations

from fastapi import APIRouter, Depends, HTTPException

from .deps import get_store
from .models import (
    OptimizationApplyRequest,
    OptimizationApplyResponse,
    OptimizationStatusResponse,
)
from .storage import InMemoryStore

router = APIRouter()


@router.post("/iot/optimization/apply", response_model=OptimizationApplyResponse)
def apply_optimization(
    payload: OptimizationApplyRequest,
    store: InMemoryStore = Depends(get_store),
):
    """
    Receives an optimization scenario generated by Forecast & Optimization.
    Spec: POST /iot/optimization/apply
    """
    sc = store.save_optimization(
        scenario_id=payload.scenarioId,
        generated_at=payload.generatedAt,
        actions=[a.dict() for a in payload.actions],
    )

    # Demo behavior: mark some progress
    if sc.total_actions == 0:
        store.set_optimization_progress(sc.scenario_id, 0, status="completed")
    else:
        store.set_optimization_progress(sc.scenario_id, 1)

    return OptimizationApplyResponse(status="accepted", scenarioId=sc.scenario_id)


@router.get("/iot/optimization/status/{scenarioId}", response_model=OptimizationStatusResponse)
def optimization_status(
    scenarioId: str,
    store: InMemoryStore = Depends(get_store),
):
    """
    Returns execution progress of an optimization scenario.
    Spec: GET /iot/optimization/status/{scenarioId}
    """
    sc = store.get_optimization(scenarioId)
    if not sc:
        raise HTTPException(status_code=404, detail="Scenario not found")

    return OptimizationStatusResponse(
        scenarioId=sc.scenario_id,
        status=sc.status,
        actionsCompleted=sc.actions_completed,
        totalActions=sc.total_actions,
    )
